defmodule MobDev.ReleaseScriptTest do
  use ExUnit.Case, async: true

  # Asserts the SHAPE of the bash script generated by `mix mob.release`.
  #
  # Why these exist: between mob_dev 0.3.27 and 0.3.31 the release script
  # accreted ~half a dozen distinct fixes for App Store Connect validator
  # errors (strip .so/.a from bundle, full DT* plist key set, ditto
  # packaging flags, MOB_RELEASE on mob_nif.m, etc.). Every fix was
  # discovered the slow way — uploading to App Store, reading Apple's
  # rejection email, fixing, re-uploading. Each round trip cost minutes
  # plus a CFBundleVersion bump.
  #
  # These tests catch any accidental regression of those fixes at
  # `mix test` time. They don't EXECUTE the script (that needs Xcode +
  # a paid Apple Developer account); they just check that the bash
  # commands we depend on are present.

  alias MobDev.Release

  setup_all do
    {:ok, sh: Release.release_device_sh()}
  end

  describe "Apple bundle policy: strip disallowed binaries" do
    # Apple error 90171 — `.so`, `.a`, and standalone executables in the
    # bundle. Apple permits exactly one Mach-O per `.app` (the
    # CFBundleExecutable). Static archives are linked into the main
    # binary; loadable libs and standalone CLIs must be stripped.

    test "deletes all .so files from the bundled OTP tree", %{sh: sh} do
      assert sh =~ ~s|find "$OTP_BUNDLE" -type f \\( -name "*.so"|
    end

    test "deletes all .a files from the bundled OTP tree", %{sh: sh} do
      assert sh =~ ~r/find "\$OTP_BUNDLE" -type f.*-name "\*\.a".*-delete/
    end

    test "deletes priv/bin/ standalone executables (memsup, cpu_sup, …)", %{sh: sh} do
      assert sh =~ ~s|find "$OTP_BUNDLE" -path "*/priv/bin/*" -type f -delete|
    end

    test "deletes erts-*/bin/ standalone executables (erl_call, erlexec, …)", %{sh: sh} do
      assert sh =~ ~r|find "\$OTP_BUNDLE/\$ERTS_VSN/bin" -type f -delete|
    end

    test "drops unused OTP libs the framework doesn't need", %{sh: sh} do
      # The strip is a `for prefix in <names>; do rm -rf
      # "$OTP_BUNDLE/lib/$prefix-"* ; done` loop, so each prefix appears
      # in the loop's word list rather than spelled out per line. Locate
      # the loop and assert the prefixes are in its head.
      [_, after_for] = String.split(sh, "for prefix in ", parts: 2)
      [loop_head, _] = String.split(after_for, "; do", parts: 2)

      # If apps emerge that DO need one of these, drop it from the strip
      # set in lib/mob_dev/release.ex AND from this test list.
      #
      # `ssh` stripped 2026-05-06 — empirical snapshot from a running
      # pigeon iOS-sim build showed 0 of 43 ssh modules ever loaded.
      # No mob app should need a runtime SSH client/server.
      for prefix <- ~w(megaco runtime_tools erl_interface os_mon wx et eunit
                       observer debugger diameter edoc tools snmp dialyzer
                       syntax_tools parsetools xmerl reltool inets ftp tftp
                       ssh) do
        assert loop_head =~ prefix,
               "expected the OTP-strip loop to drop #{prefix}-* libs"
      end

      # And the body of the loop should actually rm under $OTP_BUNDLE/lib.
      # The loop body lives inside a `bash -c '...'` invocation (so each step
      # gets a [SLIM:tag] size delta), which means $OTP_BUNDLE is unquoted out
      # of the single-quoted heredoc — match either form.
      assert sh =~ ~r/rm -rf "(?:'")?\$OTP_BUNDLE(?:"')?\/lib\/\$prefix-"/
    end

    test "does NOT strip compiler — Ecto.Migrator needs it at runtime", %{sh: sh} do
      # Regression guard for the 2026-05-21 TestFlight crash: stripping
      # compiler-* removed :compiler, which Ecto.Migrator requires to
      # Code.compile_file the .exs migrations. The BEAM crashed during
      # boot with {:badmatch, {:error, :enoent, :"compiler.app"}} before
      # the first screen rendered — splash spinner forever.
      [_, after_for] = String.split(sh, "for prefix in ", parts: 2)
      [loop_head, _] = String.split(after_for, "; do", parts: 2)

      refute loop_head =~ ~r/\bcompiler\b/,
             "compiler must NOT be in the OTP-strip loop — Ecto.Migrator " <>
               "compiles .exs migrations at runtime and needs :compiler"
    end
  end

  describe "native sources kept in sync with the framework" do
    test "globs all mob Swift sources so new files auto-compile", %{sh: sh} do
      # The release swiftc input globs $MOB_DIR/ios/*.swift rather than listing
      # files by name, so a newly-added mob Swift file (e.g. MobGpuView.swift,
      # which MobRootView references) is compiled without a release.ex edit.
      # Listing files by name is exactly how master's iOS build broke when
      # MobGpuView.swift landed but older builds didn't know to compile it.
      assert sh =~ ~s|"$MOB_DIR"/ios/*.swift|
      refute sh =~ ~s|"$MOB_DIR/ios/MobRootView.swift"|
    end

    test "screenshot NIF is opt-in: mob_nif.m compile passes -DMOB_ENABLE_SCREENSHOT only when set",
         %{sh: sh} do
      # `${VAR:+flag}` expands to the flag only when MOB_ENABLE_SCREENSHOT is non-empty
      # (set by ios_release_screenshot: true), so a default release build never gets it
      # and the public-API screenshot NIF stays stripped unless the host opts in.
      assert sh =~ ~s|${MOB_ENABLE_SCREENSHOT:+-DMOB_ENABLE_SCREENSHOT}|
      # Still always stripping the private-input harness via -DMOB_RELEASE.
      assert sh =~ "-DMOB_RELEASE"
    end

    test "compiles the per-app generated driver_tab, not $MOB_DIR/ios", %{sh: sh} do
      # driver_tab moved to priv/generated (regenerated per-app via
      # `mix mob.regen_driver_tab`). The legacy $MOB_DIR/ios/driver_tab_ios.c
      # path no longer exists.
      assert sh =~ ~s|-c "priv/generated/driver_tab_ios.c"|
      refute sh =~ ~s|"$MOB_DIR/ios/driver_tab_ios.c"|
    end

    test "links crypto.a + libcrypto.a (crypto_nif_init / TLS)", %{sh: sh} do
      assert sh =~ ~s|$OTP_ROOT/$ERTS_VSN/lib/crypto.a|
      assert sh =~ ~s|$OTP_ROOT/$ERTS_VSN/lib/libcrypto.a|
    end

    test "generates + links the erl_errno_id_unknown weak stub", %{sh: sh} do
      # libbeam.a's erl_posix_str.o references erl_errno_id_unknown but the
      # bundled OTP doesn't define it → undefined-symbol link error.
      assert sh =~ "erl_errno_id_unknown"
      assert sh =~ ~s|"$BUILD_DIR/erl_errno_id_compat.o"|

      # The shim must be written with a real newline: this is a ~S (raw) heredoc,
      # so `printf '%s\\n'` reaches bash verbatim and emits a literal backslash-n
      # into the C file (clang rejects the trailing `}\n`). `printf '%s\n'` (one
      # backslash) emits a newline. Regression guard for that escaping bug.
      assert sh =~ ~S|printf '%s\n' '__attribute__((weak))|
      refute sh =~ ~S|printf '%s\\n'|
    end

    test "does NOT compile the old md5/no-op crypto+ssl shims into BEAMS_DIR", %{sh: sh} do
      # The shims shadowed the real crypto-5.9/ssl-11.7 beams on the -pa
      # path, breaking TLS (`:ssl.versions/0 undefined`). The runtime ships
      # real crypto (linked via crypto.a) + ssl, so the shims must not be
      # generated. See decisions/2026-05-25-real-crypto-ssl-on-device.md.
      refute sh =~ "Crypto shim for iOS"
      refute sh =~ "SSL shim for iOS"
      refute sh =~ ~s|erlc -o "$BEAMS_DIR" "$SSL_TMP/ssl.erl"|
      refute sh =~ ~s|erlc -o "$BEAMS_DIR" "$CRYPTO_TMP/crypto.erl"|
    end
  end

  describe "activated-plugin NIFs are compiled + linked" do
    # driver_tab_ios references each activated plugin's <module>_nif_init.
    # Before this fix the release script hand-compiled a fixed object list and
    # never touched plugins, so any app with NIF plugins (all of them) died at
    # link with "Undefined symbols: _<module>_nif_init". The dev build already
    # compiled these via build.zig -Dplugin_c_nifs; this brings the release
    # path to parity.

    test "loops over MOB_PLUGIN_IOS_NIF_SOURCES and compiles each", %{sh: sh} do
      assert sh =~ ~s|for SRC in $MOB_PLUGIN_IOS_NIF_SOURCES|
    end

    test "derives the NIF libname from the source basename", %{sh: sh} do
      # basename minus extension → STATIC_ERLANG_NIF_LIBNAME, so ERL_NIF_INIT
      # emits <name>_nif_init matching the driver table.
      assert sh =~ ~s|NAME=$(basename "$SRC"); NAME="${NAME%.*}"|
      assert sh =~ ~s|-DSTATIC_ERLANG_NIF -DSTATIC_ERLANG_NIF_LIBNAME="$NAME"|
    end

    test "compiles ObjC (.m) sources with -fobjc-arc and always -fmodules", %{sh: sh} do
      # -fmodules autolinks every framework the source @imports (a plugin may
      # import frameworks beyond its manifest set, e.g. Accelerate).
      assert sh =~ ~s|*.m) ARC="-fobjc-arc" ;;|
      assert sh =~ ~s|$CC $ARC -fmodules $IFLAGS|
    end

    test "adds the compiled plugin objects to the final link line", %{sh: sh} do
      assert sh =~ ~r/PLUGIN_OBJS="\$PLUGIN_OBJS \$BUILD_DIR\/\$NAME\.o"/
      # $PLUGIN_OBJS is on the swiftc link command (unquoted so it word-splits).
      assert sh =~ ~r/"\$BUILD_DIR\/erl_errno_id_compat\.o" \\\n\s*\$PLUGIN_OBJS \\/
    end

    test "passes each declared framework explicitly to the linker", %{sh: sh} do
      assert sh =~ ~s|for FW in $MOB_PLUGIN_IOS_FRAMEWORKS|
      assert sh =~ ~s|-Xlinker -framework -Xlinker $FW|
      assert sh =~ ~s|$PLUGIN_FRAMEWORK_FLAGS \\|
    end
  end

  describe "test harness compiled out of release builds" do
    # Apple error code 50 — non-public selectors. Mob's synthetic-touch
    # NIFs (`tap_xy`, `swipe_xy`, …) use private UIKit APIs. mob 0.5.12
    # wraps them in `#if !MOB_RELEASE`; mob_dev 0.3.29 added the
    # `-DMOB_RELEASE` flag to mob_nif.m's compile command (was
    # previously only on mob_beam.m). Both are needed.

    test "compiles mob_nif.m with -DMOB_RELEASE", %{sh: sh} do
      # Find the mob_nif.m compile invocation specifically. The flag
      # must land on this file's $CC line, not just on mob_beam.m which
      # uses a separate compile invocation. (Earlier bug: mob_dev 0.3.28
      # had -DMOB_RELEASE only on mob_beam.m, so the test-harness
      # `#if !MOB_RELEASE` in mob_nif.m always evaluated true.)
      mob_nif_block = nif_compile_block(sh, "mob_nif.m")
      assert mob_nif_block =~ "DMOB_RELEASE"
    end

    test "compiles mob_beam.m with -DMOB_RELEASE", %{sh: sh} do
      mob_beam_block = nif_compile_block(sh, "mob_beam.m")
      assert mob_beam_block =~ "DMOB_RELEASE"
    end
  end

  describe "Info.plist build-environment keys (DT* set)" do
    # Apple error 90534 — "Unsupported SDK or Xcode version". Apple's
    # validator cross-references DTSDKBuild + DTXcodeBuild against an
    # allow-list of accepted Xcode releases. Without the full DT* set,
    # the upload is rejected even when Xcode itself is current.

    test "emits MinimumOSVersion (error 90065/90530)", %{sh: sh} do
      assert sh =~ ":MinimumOSVersion"
    end

    test "emits DTPlatformName (error 90507)", %{sh: sh} do
      assert sh =~ ":DTPlatformName"
    end

    test "emits the full DT* environment set", %{sh: sh} do
      for key <- ~w(DTSDKName DTSDKBuild DTPlatformVersion DTPlatformBuild
                    DTXcode DTXcodeBuild DTCompiler BuildMachineOSBuild) do
        assert sh =~ "\"#{key}=", "expected the DT* loop to emit #{key}"
      end
    end

    test "emits UIDeviceFamily defaulting to iPhone-only (error 90102)", %{sh: sh} do
      # Two PlistBuddy calls: one Add :UIDeviceFamily as an array, one
      # Add :UIDeviceFamily:0 as integer 1 (iPhone). Apps that want
      # universal can override in their source Info.plist before this
      # block runs (the Add will fail and we won't overwrite).
      assert sh =~ "Add :UIDeviceFamily array"
      assert sh =~ "Add :UIDeviceFamily:0 integer 1"
    end

    test "emits CFBundleSupportedPlatforms = iPhoneOS (error 90562)", %{sh: sh} do
      assert sh =~ "Add :CFBundleSupportedPlatforms array"
      assert sh =~ "Add :CFBundleSupportedPlatforms:0 string iPhoneOS"
    end

    test "DTXcode encoding uses MAJOR×100 + MINOR×10 + PATCH (4-digit form)", %{sh: sh} do
      # Encoding bug history: first attempt used MAJOR×1000 which
      # produced 5 digits ("26040" for Xcode 26.4) and Apple's allow-list
      # rejected the exact match. Correct form is 4 digits — Xcode 16.4
      # → 1640, Xcode 26.4 → 2640.
      assert sh =~ ~r/XCODE_MAJOR \* 100 \+ XCODE_MINOR \* 10 \+ XCODE_PATCH/
    end
  end

  describe "IPA packaging preserves bundle structure" do
    # Apple error 90071 — CodeResources must be a symbolic link.
    # `zip -r` flattens symlinks; `ditto -c -k` preserves them. The
    # extra ditto flags strip macOS resource forks and quarantine
    # attributes that would otherwise emit `__MACOSX/` and `._<file>`
    # AppleDouble sidecars that Apple's validator can flag.

    test "uses ditto, not zip, for IPA packaging", %{sh: sh} do
      assert sh =~ "ditto -c -k"

      refute sh =~ "zip -qr",
             "release script still uses `zip -qr` — should be `ditto -c -k …` for symlink preservation"
    end

    test "ditto invocation strips macOS-only resource forks / xattrs / quarantine", %{sh: sh} do
      # All three flags matter — without them, ditto preserves
      # extended attributes from the OTP cross-build cache and emits
      # `._<file>` AppleDouble sidecars inside the IPA.
      assert sh =~ "--norsrc"
      assert sh =~ "--noextattr"
      assert sh =~ "--noqtn"
    end

    test "preserves --keepParent for the Payload/ wrapper directory", %{sh: sh} do
      assert sh =~ "--keepParent"
    end

    test "uses cp -RP (not cp -R) when staging the .app for ditto", %{sh: sh} do
      # cp -R follows symlinks and turns them into regular files; -P
      # preserves them. Without -P, the codesign-created CodeResources
      # symlink gets flattened before ditto sees it.
      assert sh =~ "cp -RP"
    end

    test "strips AppleDouble sidecars defensively before ditto", %{sh: sh} do
      assert sh =~ "dot_clean"
      assert sh =~ ~s|find "$IPA_STAGE/Payload" -name '._*' -delete|
    end
  end

  describe "code signing" do
    # Distribution signing (no get-task-allow), separate from dev
    # signing. The script reads the distribution identity + profile
    # UUID from env vars set by Release.build_ipa/1's resolution step.

    test "signs with --options runtime + --timestamp (App Store requirements)", %{sh: sh} do
      assert sh =~ "--timestamp"
      assert sh =~ "--options runtime"
    end

    test "embeds the App Store provisioning profile", %{sh: sh} do
      assert sh =~ ~s|cp "$PROFILE" "$APP/embedded.mobileprovision"|
    end

    test "verifies the signature after applying it", %{sh: sh} do
      assert sh =~ ~s|codesign --verify --deep --strict|
    end

    test "entitlements omit get-task-allow (would block App Store)", %{sh: sh} do
      # The entitlements heredoc inside the script must NOT contain
      # `<key>get-task-allow</key>`. That key is only valid for
      # dev/debug builds — App Store rejects bundles signed with it
      # set true. Note: the string `get-task-allow` DOES appear in a
      # `# Code signing (distribution, no get-task-allow)` comment
      # elsewhere in the script, so we look only inside the
      # heredoc body.
      [_, after_open] = String.split(sh, "<< ENTEOF\n", parts: 2)
      [heredoc_body, _] = String.split(after_open, "\nENTEOF\n", parts: 2)

      refute heredoc_body =~ "get-task-allow",
             "release entitlements heredoc must not contain get-task-allow — App Store rejects builds signed with it"
    end
  end

  # Returns the lines of script around a `-c "$MOB_DIR/ios/<file>"`
  # compile invocation — enough to see the flags on the same $CC call.
  # Each NIF compile is a multi-line `$CC ... -c <file> -o <out>`
  # invocation; we take the chunk from the previous blank line up to
  # and including the `-c <file>` arg.
  defp nif_compile_block(sh, file) do
    sh
    |> String.split("\n\n")
    |> Enum.find(fn block -> String.contains?(block, "-c \"$MOB_DIR/ios/#{file}\"") end)
    |> Kernel.||("")
  end

  describe "OTP runtime is bundled before strip pass" do
    # Sanity: the script must actually copy the OTP runtime tree before
    # the strip pass deletes things from it. Order of operations matters.

    test "copies $OTP_ROOT/lib/ before the strip pass runs", %{sh: sh} do
      [bundle, strip] =
        sh
        |> String.split("Stripping App-Store-disallowed binaries", parts: 2)

      assert bundle =~ ~s|rsync -a --delete "$OTP_ROOT/lib/"|,
             "expected OTP lib/ to be rsynced into the bundle before the strip pass"

      assert strip =~ "find \"$OTP_BUNDLE\" -type f"
    end
  end

  describe "MOB_SLIM gating and per-step traceability" do
    # Every slim strip step is wrapped in a `slim_step <tag> ...` bash
    # function call. The function emits `[SLIM:<tag>] N KB → M KB (-D KB)`
    # so a broken build can be bisected to a single step from build logs.
    # Both the gating shape and the tag set are part of the contract.

    test "Apple-policy strips are NOT gated (always run for App Store validity)", %{sh: sh} do
      # The .so/.a/standalone-bin strips happen above the MOB_SLIM check —
      # `--no-slim` builds still need to pass App Store validation.
      [apple, _slim] = String.split(sh, ~s|if [ "${MOB_SLIM:-1}" = "1" ]; then|, parts: 2)
      assert apple =~ ~s|find "$OTP_BUNDLE" -type f \\( -name "*.so"|
      assert apple =~ ~s|find "$OTP_BUNDLE" -path "*/priv/bin/*" -type f -delete|
    end

    test "slim block is gated on MOB_SLIM env var (default on for release)", %{sh: sh} do
      assert sh =~ ~s|if [ "${MOB_SLIM:-1}" = "1" ]; then|,
             "release.ex must default MOB_SLIM=1 — `mix mob.release --no-slim` opts out"
    end

    test "skip path emits [SLIM:skipped] when MOB_SLIM=0", %{sh: sh} do
      assert sh =~ "[SLIM:skipped] MOB_SLIM=0",
             "no-slim builds must announce themselves so the build log makes the choice obvious"
    end

    test "defines a slim_step bash helper that prints [SLIM:<label>] size delta", %{sh: sh} do
      assert sh =~ "slim_step() {",
             "expected a slim_step() bash helper to be defined inside the slim block"

      assert sh =~ ~s|printf "[SLIM:%s] %s KB → %s KB  (-%s KB)\\n"|,
             "slim_step must emit the [SLIM:tag] before/after/delta line — it's the grep target docs use"
    end

    test "every strip step routes through slim_step <tag>", %{sh: sh} do
      # If a step is added without going through slim_step, it won't show
      # up in the [SLIM:...] log and a regression in that step won't be
      # bisectable from the build output.
      for tag <- ~w(prefix_libs foreign_apps dedup_versions src_and_headers beam_chunks) do
        assert sh =~ "slim_step #{tag}",
               "expected slim_step invocation for tag `#{tag}`"
      end
    end

    test "main-binary symbol strip is gated on MOB_SLIM", %{sh: sh} do
      # `xcrun strip -x` rewrites the Mach-O — must NOT happen on
      # `--no-slim` builds where the developer wants debug symbols
      # preserved on the release-shaped binary.
      [_, after_first_gate] = String.split(sh, ~s|if [ "${MOB_SLIM:-1}" = "1" ]; then|, parts: 2)
      assert after_first_gate =~ "xcrun strip -x"
    end
  end
end
